apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstspringapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstspringapp
  template:
    metadata:
      labels:
        app: firstspringapp
    spec:
      containers:
        - name: firstspringapp
          image: zmehibr/firstspringapp:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
